### ISSUE TITLE
extraction error

### ISSUE THREAD

**Issue by rui-chen-1** [phiresky/pandoc-url2cite#13]
Thank you for creating this wonderful tool!
However, today I have been trying both methods of adding the link but keep getting the same error below:

```
fetching citation from url https://www.sciencedirect.com/science/article/pii/S0376738818326115
extraction error Error: could not fetch citation from https://www.sciencedirect.com/science/article/pii/S0376738818326115: {"type":"[https://mediawiki.org/wiki/HyperSwitch/errors/not_found","title":"Not](https://mediawiki.org/wiki/HyperSwitch/errors/not_found%22,%22title%22:%22Not) found.","method":"get","uri":"/en.wikipedia.org/v1/data/citation/bibtex/https%3A%2F%[2Fwww.sciencedirect.com](http://2fwww.sciencedirect.com/)%2Fscience%2Farticle%2Fpii%2FS0376738818326115"}
at getCslForUrl (/opt/homebrew/lib/node_modules/pandoc-url2cite/dist/index.js:51:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Url2Cite.getCslForUrlCached (/opt/homebrew/lib/node_modules/pandoc-url2cite/dist/index.js:80:19)
at async Object.astTransformer [as single] (/opt/homebrew/lib/node_modules/pandoc-url2cite/dist/index.js:169:17)
at async walk (/opt/homebrew/lib/node_modules/pandoc-url2cite/node_modules/pandoc-filter/index.js:60:28)
at async walk (/opt/homebrew/lib/node_modules/pandoc-url2cite/node_modules/pandoc-filter/index.js:79:22)
at async walk (/opt/homebrew/lib/node_modules/pandoc-url2cite/node_modules/pandoc-filter/index.js:67:32)
at async walk (/opt/homebrew/lib/node_modules/pandoc-url2cite/node_modules/pandoc-filter/index.js:79:22)
at async Object.filter (/opt/homebrew/lib/node_modules/pandoc-url2cite/node_modules/pandoc-filter/index.js:178:13)
at async Url2Cite.transform (/opt/homebrew/lib/node_modules/pandoc-url2cite/dist/index.js:236:16)
Error running filter pandoc-url2cite:
Filter returned error status 1
```

Is there a easy fix here? I am using the same pandoc command in README here.

**Comment by phiresky** [comment]
It looks like you have some parsing error. Please send the content of your document (/ a minimal reproduction)
